In [1]:
import numpy as np;
import pandas as pd;

In [2]:
df=pd.read_csv('covid_toy.csv')

In [3]:
df.head(4)

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No

In [4]:
df.shape

(100, 6)

In [5]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

## Aam Zindagi

In [7]:
## we will fill nan value
from sklearn.impute import SimpleImputer
si=SimpleImputer()

In [8]:
X_train_fever=si.fit_transform(X_train[['fever']])
X_test_fever=si.transform(X_test[['fever']])

In [9]:
X_train_fever.shape

(80, 1)

In [10]:
X_test_fever.shape

(20, 1)

In [11]:
X_train.head(5)
X_train['city'].unique()

array(['Mumbai', 'Kolkata', 'Delhi', 'Bangalore'], dtype=object)

In [28]:
from sklearn.preprocessing import OrdinalEncoder,OrdinalEncoder

In [13]:
#Ordinalencoding the fever column
oe=OrdinalEncoder(categories=[['Mild','Strong']])

In [14]:
X_train_cough=oe.fit_transform(X_train[['cough']])
X_test_cough=oe.transform(X_test[['cough']])
X_test_cough.shape

(20, 1)

In [15]:
##one hot encodding of gender,city
from sklearn.preprocessing import OneHotEncoder

In [16]:
oeh=OneHotEncoder(drop='first',sparse_output=False)
X_train_gender_city=oeh.fit_transform(X_train[['gender','city']])
X_test_gender_city=oeh.transform(X_test[['gender','city']])
X_train_gender_city.shape

(80, 4)

In [17]:
##extracing  age from X-train and X-test
X_train_age=X_train.drop(columns=['gender','fever','cough','city']).values
X_test_age=X_test.drop(columns=['gender','fever','cough','city']).values
X_test.shape

(20, 5)

In [18]:
## merging the Columns
X_train_transformed=np.concatenate((X_train_age,X_train_fever,X_train_cough,X_train_gender_city),axis=1)
X_test_transformed=np.concatenate((X_test_age,X_test_fever,X_test_cough,X_test_gender_city),axis=1)
X_train_final=pd.DataFrame(X_train_transformed)
X_test_final=pd.DataFrame(X_test_transformed)

## Mentos Zindagi

In [32]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder

In [36]:
X_train.head(3)

    age  gender  fever   cough     city
49   44    Male  104.0    Mild   Mumbai
46   19  Female  101.0    Mild   Mumbai
15   70    Male  103.0  Strong  Kolkata

In [39]:
Transformer=ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]) , ['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first') , ['gender','city'])
],remainder='passthrough')
output=Transformer.fit_transform(X_train)

In [40]:
print(output)

[[104.           0.           1.           0.           0.
    1.          44.        ]
 [101.           0.           0.           0.           0.
    1.          19.        ]
 [103.           1.           1.           0.           1.
    0.          70.        ]
 [100.           0.           1.           0.           1.
    0.          27.        ]
 [101.           1.           0.           1.           0.
    0.          34.        ]
 [100.           1.           0.           0.           0.
    0.          19.        ]
 [101.           1.           1.           0.           0.
    0.          47.        ]
 [100.76712329   0.           1.           0.           0.
    1.          23.        ]
 [100.           0.           0.           0.           1.
    0.          19.        ]
 [100.76712329   0.           1.           1.           0.
    0.          38.        ]
 [102.           0.           1.           0.           0.
    0.          64.        ]
 [104.           1.           0.           1.           0.
    0.          34.        ]
 [102.           0.           1.           0.           0.
    1.          74.        ]
 [103.           0.           1.           0.           1.
    0.          60.        ]
 [101.           0.           1.           1.           0.
    0.          42.        ]
 [ 98.           1.           0.           0.           1.
    0.          71.        ]
 [101.           0.           0.           0.           0.
    1.          81.        ]
 [100.76712329   1.           1.           0.           1.
    0.          71.        ]
 [101.           0.           1.           1.           0.
    0.          15.        ]
 [ 99.           0.           0.           0.           0.
    0.          22.        ]
 [ 98.           1.           0.           0.           1.
    0.          10.        ]
 [102.           1.           1.           1.           0.
    0.          20.        ]
 [100.           1.           0.           0.           1.
    0.          11.        ]
 [102.           1.           0.           0.           0.
    0.          82.        ]
 [ 98.           0.           0.           1.           0.
    0.          80.        ]
 [100.           1.           0.           0.           1.
    0.          13.        ]
 [100.76712329   0.           0.           1.           0.
    0.          75.        ]
 [103.           0.           0.           0.           1.
    0.          48.        ]
 [103.           1.           1.           0.           0.
    0.          46.        ]
 [100.           0.           0.           0.           1.
    0.           5.        ]
 [102.           0.           0.           0.           0.
    0.          69.        ]
 [100.76712329   1.           1.           0.           1.
    0.          79.        ]
 [ 98.           1.           1.           0.           0.
    0.          12.        ]
 [101.           1.           0.           1.           0.
    0.          68.        ]
 [104.           0.           1.           0.           1.
    0.          51.        ]
 [ 98.           1.           0.           0.           0.
    1.          81.        ]
 [100.           0.           1.           1.           0.
    0.          27.        ]
 [ 99.           1.           0.           0.           1.
    0.          25.        ]
 [102.           0.           0.           1.           0.
    0.          49.        ]
 [ 98.           0.           1.           0.           1.
    0.          24.        ]
 [ 99.           1.           1.           0.           0.
    0.          66.        ]
 [104.           1.           0.           0.           1.
    0.          54.        ]
 [101.           1.           1.           0.           0.
    0.          14.        ]
 [104.           0.           0.           0.           1.
    0.          17.        ]
 [104.           0.           0.           0.           1.
    0.           6.        ]
 [102.           1.           0.           1.           0.
    0.          33.        ]
 [ 99.           0.           1.           0.           0.
    0.          72.        ]
 [103.           0.           0.           0.           0.
    0.          16.        ]
 [ 98.           0.           0.           0.           1.
    0.          26.        ]
 [ 98.           0.           1.           0.           0.
    0.          73.        ]
 [102.           0.           1.           0.           1.
    0.           5.        ]
 [ 98.           1.           0.           1.           0.
    0.          40.        ]
 [100.76712329   0.           0.           0.           0.
    0.          84.        ]
 [102.           1.           0.           0.           0.
    0.          24.        ]
 [104.           0.           0.           0.           0.
    0.          12.        ]
 [ 99.           0.           0.           0.           0.
    1.          60.        ]
 [ 98.           0.           0.           0.           0.
    1.          65.        ]
 [ 99.           0.           1.           1.           0.
    0.          65.        ]
 [104.           0.           1.           0.           0.
    0.          51.        ]
 [100.           0.           1.           0.           0.
    0.          10.        ]
 [100.76712329   1.           0.           0.           0.
    0.          42.        ]
 [ 99.           0.           0.           0.           0.
    1.          14.        ]
 [103.           0.           0.           0.           1.
    0.          50.        ]
 [ 98.           0.           0.           0.           0.
    0.          64.        ]
 [100.           0.           1.           0.           0.
    0.          11.        ]
 [104.           0.           1.           0.           1.
    0.          16.        ]
 [ 99.           0.           1.           0.           0.
    0.          65.        ]
 [ 98.           0.           1.           1.           0.
    0.          83.        ]
 [101.           0.           0.           0.           1.
    0.           8.        ]
 [101.           0.           0.           0.           0.
    0.          38.        ]
 [101.           0.           0.           0.           0.
    0.          20.        ]
 [101.           1.           0.           0.           1.
    0.          51.        ]
 [101.           0.           0.           0.           0.
    1.          65.        ]
 [100.           0.           1.           0.           0.
    0.          80.        ]
 [101.           0.           1.           1.           0.
    0.          19.        ]
 [103.           0.           0.           0.           1.
    0.          69.        ]
 [102.           1.           0.           0.           1.
    0.          82.        ]
 [ 98.           1.           1.           0.           1.
    0.          34.        ]
 [101.           0.           0.           0.           1.
    0.          83.        ]
 [ 98.           0.           0.           0.           1.
    0.          31.        ]]